[package]
name = "mlua"
version = "0.2.2"
authors = ["Aleksandr Orlenko <zxteam@pm.me>", "kyren <catherine@chucklefish.org>"]
edition = "2018"
repository = "https://github.com/khvzak/mlua"
documentation = "https://docs.rs/mlua"
readme = "README.md"
keywords = ["lua", "luajit"]
categories = ["api-bindings"]
license = "MIT"
links = "lua"
build = "build/main.rs"
description = """
High level bindings to Lua 5.1/5.2/5.3 (including LuaJIT)
with support of writing native lua modules in Rust.
"""

[badges]
# github-actions = { repository = "khvzak/mlua", workflow = "CI" }

[workspace]
members = [
    "mlua_derive",
]

[features]
default = ["lua53"]
lua53 = []
lua52 = []
lua51 = []
luajit = []
vendored = ["lua-src", "luajit-src"]

[dependencies]
num-traits = { version = "0.2.6" }
bstr = { version = "0.2", features = ["std"], default_features = false }
futures = { version = "0.3.1" }
lazy_static = { version = "1.4" }

[build-dependencies]
cc = { version = "1.0" }
pkg-config = { version = "0.3.11" }
lua-src = { version = "535.0.1", optional = true }
luajit-src = { version = "210.0.0", optional = true }

[dev-dependencies]
rustyline = "5.0"
criterion = "0.2.0"
trybuild = "1.0"

[[bench]]
name = "benchmark"
harness = false
